"""add key_moments_json to session

Revision ID: 26711688d9b5
Revises: b2712b81f716
Create Date: 2026-03-08 17:27:53.006199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26711688d9b5'
down_revision: Union[str, Sequence[str], None] = 'b2712b81f716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('key_moments_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'key_moments_json')
    # ### end Alembic commands ###
