"""add ai features

Revision ID: b2712b81f716
Revises: 68f7ef19cbfa
Create Date: 2026-03-07 17:40:57.487076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2712b81f716'
down_revision: Union[str, Sequence[str], None] = '68f7ef19cbfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('questions_asked_json', sa.JSON(), nullable=True))
    op.add_column('sessions', sa.Column('talk_listen_ratios_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'talk_listen_ratios_json')
    op.drop_column('sessions', 'questions_asked_json')
    # ### end Alembic commands ###
